const router = require("express").Router();
const mongoose = require("mongoose");
const PDFDocument = require("pdfkit");

const ensureAuth = require("../middleware/ensureAuth");
const PredictionResult = require("../models/PredictionResult");

const toPercentage = (value) => {
  if (typeof value !== "number") return "N/A";
  return `${(value * 100).toFixed(1)}%`;
};

const toDisplay = (value, decimals = 2) => {
  if (typeof value !== "number") return "N/A";
  return value.toFixed(decimals);
};

const yesNoUnknown = (value) => {
  if (value === true) return "Yes";
  if (value === false) return "No";
  return "Not Provided";
};

router.get("/download/:id", ensureAuth, async (req, res) => {
  try {
    const { id } = req.params;
    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({ message: "Invalid report id." });
    }

    const result = await PredictionResult.findOne({
      _id: id,
      user: req.user._id,
    }).lean();

    if (!result) {
      return res.status(404).json({ message: "Screening result not found." });
    }

    const generatedAt = new Date();
    const predictionDate = result.predictionDate || result.createdAt;
    const filename = `neurosense-report-${id}.pdf`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=\"${filename}\"`,
    );

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Title: "NeuroSense Dementia Screening Report",
        Author: "NeuroSense",
      },
    });

    doc.pipe(res);

    // Header
    doc
      .fontSize(22)
      .fillColor("#1f3a8a")
      .text("NeuroSense", { align: "left" })
      .moveDown(0.2)
      .fontSize(14)
      .fillColor("#111827")
      .text("Dementia Screening Report")
      .moveDown(1);

    doc
      .fontSize(10)
      .fillColor("#4b5563")
      .text(`Generated: ${generatedAt.toLocaleString()}`)
      .text(`Prediction Date: ${new Date(predictionDate).toLocaleString()}`)
      .text(`Report ID: ${String(result._id)}`)
      .moveDown(1);

    // Patient / user section
    doc
      .fontSize(12)
      .fillColor("#111827")
      .text("Patient & Account Information", { underline: true })
      .moveDown(0.4)
      .fontSize(11)
      .text(`Name: ${req.user.name || "N/A"}`)
      .text(`Email: ${req.user.email || "N/A"}`)
      .text(`Patient ID: ${result.patientId || "N/A"}`)
      .moveDown(1);

    // Risk section
    doc
      .fontSize(12)
      .text("Risk Assessment Summary", { underline: true })
      .moveDown(0.4)
      .fontSize(11)
      .text(
        `Risk Score: ${toDisplay(result.riskScore)} (${toPercentage(result.riskScore)})`,
      )
      .text(`Risk Level: ${(result.riskLevel || "N/A").toUpperCase()}`)
      .text(`Model Confidence: ${toPercentage(result.confidence)}`)
      .text(`Model Version: ${result.modelVersion || "N/A"}`)
      .moveDown(1);

    // Cognitive tests
    doc
      .fontSize(12)
      .text("Cognitive Test Summary", { underline: true })
      .moveDown(0.4)
      .fontSize(11)
      .text(`MMSE Score: ${toDisplay(result.cognitiveTests?.mmseScore, 1)}`)
      .text(`CDR Score: ${toDisplay(result.cognitiveTests?.cdrScore, 1)}`)
      .text(`MoCA Score: ${toDisplay(result.cognitiveTests?.mocaScore, 1)}`)
      .text(
        `Education Years: ${toDisplay(result.cognitiveTests?.educationYears, 0)}`,
      )
      .text(
        `Family History: ${yesNoUnknown(result.cognitiveTests?.familyHistory)}`,
      )
      .text(
        `Physical Activity: ${
          result.cognitiveTests?.physicalActivityLevel
            ? result.cognitiveTests.physicalActivityLevel
            : "Not Provided"
        }`,
      )
      .moveDown(1);

    // Notes
    doc
      .fontSize(12)
      .text("Clinical Notes", { underline: true })
      .moveDown(0.4)
      .fontSize(11)
      .text(result.notes || "No additional notes available.")
      .moveDown(1.2);

    // Disclaimer
    doc
      .fontSize(12)
      .fillColor("#7c2d12")
      .text("Medical Disclaimer", { underline: true })
      .moveDown(0.4)
      .fontSize(10)
      .fillColor("#111827")
      .text(
        "This report is generated by an AI-assisted screening system and is intended for informational and triage support purposes only. It is not a diagnosis and must not replace professional clinical judgment.",
      )
      .moveDown(0.3)
      .text(
        "Patients with elevated risk scores should be referred to qualified healthcare professionals for comprehensive evaluation, diagnosis, and treatment planning.",
      )
      .moveDown(0.3)
      .text(
        "NeuroSense does not guarantee clinical outcomes and assumes no liability for decisions made without independent medical review.",
      );

    doc.end();
  } catch (err) {
    console.error("Report generation error:", err);
    return res.status(500).json({ message: "Failed to generate report." });
  }
});

module.exports = router;
